using System.Globalization;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using PZTools.Core.Models;

namespace PZTools.Core.Functions.Projects
{
    /// <summary>
    /// Reads and writes the small, repeatable Project Zomboid declarations which are
    /// otherwise commonly copied between mods. Generated Lua is deliberately plain so
    /// it remains useful and editable without PZTools.
    /// </summary>
    public static partial class ManagedContentService
    {
        public const string GeneratedHeader = "-- Generated by PZTools Content Managers. You can still edit this file by hand.";

        public static string GetDefaultProfessionPath(ModProject project, ModTarget target)
            => target.Build >= 42
                ? Path.Combine(target.Path, "media", "scripts", $"{SafeId(project)}_Professions.txt")
                : Path.Combine(target.Path, "media", "lua", "shared", $"{SafeId(project)}_Professions.lua");

        public static string GetDefaultTraitPath(ModProject project, ModTarget target)
            => target.Build >= 42
                ? Path.Combine(target.Path, "media", "scripts", $"{SafeId(project)}_Traits.txt")
                : Path.Combine(target.Path, "media", "lua", "shared", $"{SafeId(project)}_Traits.lua");

        public static string GetSandboxOptionsPath(ModTarget target)
            => Path.Combine(target.Path, "media", "sandbox-options.txt");

        public static IReadOnlyList<string> FindDeclarationFiles(ModTarget target, bool professions)
        {
            if (!Directory.Exists(target.Path))
                return Array.Empty<string>();
            var luaNeedle = professions ? "ProfessionFactory.addProfession" : "TraitFactory.addTrait";
            var scriptNeedle = professions ? "character_profession_definition" : "character_trait_definition";
            return Directory.EnumerateFiles(target.Path, "*", SearchOption.AllDirectories)
                .Where(path => path.EndsWith(".lua", StringComparison.OrdinalIgnoreCase) || path.EndsWith(".txt", StringComparison.OrdinalIgnoreCase))
                .Where(path => File.ReadLines(path).Any(line =>
                    line.Contains(luaNeedle, StringComparison.Ordinal) ||
                    line.Contains(scriptNeedle, StringComparison.OrdinalIgnoreCase)))
                .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }

        public static List<ProfessionDefinition> ParseProfessions(string text)
        {
            var result = new List<ProfessionDefinition>();
            foreach (var call in FindCalls(text, "ProfessionFactory.addProfession"))
            {
                var args = SplitArguments(call.Arguments);
                if (args.Count < 4)
                    continue;
                var definition = new ProfessionDefinition
                {
                    Id = LuaString(args[0]),
                    TranslationKey = GetTextKey(args[1]),
                    Icon = LuaString(args[2]),
                    Cost = ParseInt(args[3]),
                    DescriptionKey = args.Count > 4 ? GetTextKey(args[4]) : ""
                };
                var variable = FindAssignedVariable(text, call.Start);
                if (!string.IsNullOrWhiteSpace(variable))
                {
                    foreach (Match trait in Regex.Matches(text, $"\\b{Regex.Escape(variable)}\\s*:\\s*addFreeTrait\\s*\\(\\s*(['\\\"])(?<value>.*?)\\1\\s*\\)", RegexOptions.Singleline))
                        if (!IsLineCommented(text, trait.Index))
                            definition.FreeTraits.Add(trait.Groups["value"].Value);
                    AddRecipes(definition.FreeRecipes, text, variable);
                    AddBoosts(definition.XpBoosts, text, variable);
                }
                result.Add(definition);
            }
            foreach (var definition in FindScriptDefinitions(text, "character_profession_definition"))
            {
                var properties = ParseScriptProperties(definition.Body);
                var item = new ProfessionDefinition
                {
                    Id = definition.Id,
                    TranslationKey = ScriptProperty(properties, "UIName"),
                    DescriptionKey = ScriptProperty(properties, "UIDescription"),
                    Icon = ScriptProperty(properties, "IconPathName"),
                    Cost = ParseInt(ScriptProperty(properties, "Cost"))
                };
                AddScriptList(item.FreeTraits, properties, "Traits", "FreeTraits");
                AddScriptList(item.FreeRecipes, properties, "Recipes", "FreeRecipes");
                AddScriptBoosts(item.XpBoosts, properties);
                CopyExtraProperties(item.ExtraProperties, properties,
                    "CharacterProfession", "Cost", "UIName", "UIDescription", "IconPathName", "XPBoosts", "Traits", "FreeTraits", "Recipes", "FreeRecipes");
                result.Add(item);
            }
            return result;
        }

        public static List<TraitDefinition> ParseTraits(string text)
        {
            var result = new List<TraitDefinition>();
            foreach (var call in FindCalls(text, "TraitFactory.addTrait"))
            {
                var args = SplitArguments(call.Arguments);
                if (args.Count < 5)
                    continue;
                var definition = new TraitDefinition
                {
                    Id = LuaString(args[0]),
                    TranslationKey = GetTextKey(args[1]),
                    Cost = ParseInt(args[2]),
                    DescriptionKey = GetTextKey(args[3]),
                    IsProfessionTrait = ParseBool(args[4]),
                    RemoveInMP = args.Count > 5 && ParseBool(args[5])
                };
                var variable = FindAssignedVariable(text, call.Start);
                if (!string.IsNullOrWhiteSpace(variable))
                {
                    AddBoosts(definition.XpBoosts, text, variable);
                    AddRecipes(definition.FreeRecipes, text, variable);
                }
                result.Add(definition);
            }
            foreach (var definition in FindScriptDefinitions(text, "character_trait_definition"))
            {
                var properties = ParseScriptProperties(definition.Body);
                var item = new TraitDefinition
                {
                    Id = definition.Id,
                    TranslationKey = ScriptProperty(properties, "UIName"),
                    DescriptionKey = ScriptProperty(properties, "UIDescription"),
                    Cost = ParseInt(ScriptProperty(properties, "Cost")),
                    IsProfessionTrait = ParseBool(ScriptProperty(properties, "IsProfessionTrait")),
                    RemoveInMP = ParseBool(ScriptProperty(properties, "DisabledInMultiplayer"))
                };
                AddScriptList(item.FreeRecipes, properties, "Recipes", "FreeRecipes");
                AddScriptBoosts(item.XpBoosts, properties);
                CopyExtraProperties(item.ExtraProperties, properties,
                    "CharacterTrait", "Cost", "UIName", "UIDescription", "IsProfessionTrait", "DisabledInMultiplayer", "XPBoosts", "Recipes", "FreeRecipes");
                result.Add(item);
            }
            return result;
        }

        public static string BuildProfessions(IEnumerable<ProfessionDefinition> professions, bool build42, string moduleName)
            => build42 ? BuildProfessionScript(professions, moduleName) : BuildProfessions(professions);

        public static string BuildTraits(IEnumerable<TraitDefinition> traits, bool build42, string moduleName)
            => build42 ? BuildTraitScript(traits, moduleName) : BuildTraits(traits);

        public static string FindScriptModuleName(string text, string fallback)
        {
            var match = Regex.Match(text ?? "", @"(?im)^\s*module\s+(?<name>[^\s{]+)\s*\{");
            return match.Success ? match.Groups["name"].Value : ValidateScriptToken(fallback, "module name");
        }

        public static string BuildProfessions(IEnumerable<ProfessionDefinition> professions)
        {
            var values = professions.ToList();
            ValidateUniqueIds(values.Select(x => x.Id), "profession");
            var sb = NewLuaBuilder("registerProfessions");
            var index = 0;
            foreach (var item in values)
            {
                ValidateId(item.Id, "profession");
                var variable = $"profession{++index}";
                var description = string.IsNullOrWhiteSpace(item.DescriptionKey) ? "" : $", getText({Quote(item.DescriptionKey)})";
                sb.AppendLine($"    local {variable} = ProfessionFactory.addProfession({Quote(item.Id)}, getText({Quote(item.TranslationKey)}), {Quote(item.Icon)}, {item.Cost.ToString(CultureInfo.InvariantCulture)}{description})");
                foreach (var trait in item.FreeTraits.Where(x => !string.IsNullOrWhiteSpace(x)))
                    sb.AppendLine($"    {variable}:addFreeTrait({Quote(trait.Trim())})");
                foreach (var boost in item.XpBoosts)
                    sb.AppendLine($"    {variable}:addXPBoost(Perks.{ValidatePerk(boost.Perk)}, {boost.Level.ToString(CultureInfo.InvariantCulture)})");
                foreach (var recipe in item.FreeRecipes.Where(x => !string.IsNullOrWhiteSpace(x)))
                    sb.AppendLine($"    {variable}:getFreeRecipes():add({Quote(recipe.Trim())})");
                sb.AppendLine();
            }
            return FinishLuaBuilder(sb, "registerProfessions");
        }

        public static string BuildTraits(IEnumerable<TraitDefinition> traits)
        {
            var values = traits.ToList();
            ValidateUniqueIds(values.Select(x => x.Id), "trait");
            var sb = NewLuaBuilder("registerTraits");
            var index = 0;
            foreach (var item in values)
            {
                ValidateId(item.Id, "trait");
                var variable = $"trait{++index}";
                sb.AppendLine($"    local {variable} = TraitFactory.addTrait({Quote(item.Id)}, getText({Quote(item.TranslationKey)}), {item.Cost.ToString(CultureInfo.InvariantCulture)}, getText({Quote(item.DescriptionKey)}), {LuaBool(item.IsProfessionTrait)}, {LuaBool(item.RemoveInMP)})");
                foreach (var boost in item.XpBoosts)
                    sb.AppendLine($"    {variable}:addXPBoost(Perks.{ValidatePerk(boost.Perk)}, {boost.Level.ToString(CultureInfo.InvariantCulture)})");
                foreach (var recipe in item.FreeRecipes.Where(x => !string.IsNullOrWhiteSpace(x)))
                    sb.AppendLine($"    {variable}:getFreeRecipes():add({Quote(recipe.Trim())})");
                sb.AppendLine();
            }
            return FinishLuaBuilder(sb, "registerTraits");
        }

        private static string BuildProfessionScript(IEnumerable<ProfessionDefinition> professions, string moduleName)
        {
            var values = professions.ToList();
            ValidateUniqueIds(values.Select(x => x.Id), "profession");
            var sb = new StringBuilder().Append("module ").Append(ValidateScriptToken(moduleName, "module name")).AppendLine().AppendLine("{");
            foreach (var item in values)
            {
                ValidateScriptToken(item.Id, "profession ID");
                sb.Append("    character_profession_definition ").AppendLine(item.Id).AppendLine("    {");
                AppendScriptProperty(sb, "CharacterProfession", item.Id);
                AppendScriptProperty(sb, "Cost", item.Cost.ToString(CultureInfo.InvariantCulture));
                AppendScriptProperty(sb, "UIName", item.TranslationKey);
                AppendScriptProperty(sb, "UIDescription", item.DescriptionKey);
                AppendScriptProperty(sb, "IconPathName", item.Icon);
                AppendScriptList(sb, "Traits", item.FreeTraits);
                AppendScriptList(sb, "Recipes", item.FreeRecipes);
                AppendScriptBoosts(sb, item.XpBoosts);
                foreach (var property in item.ExtraProperties)
                    AppendScriptProperty(sb, property.Key, property.Value);
                sb.AppendLine("    }");
            }
            return sb.AppendLine("}").ToString();
        }

        private static string BuildTraitScript(IEnumerable<TraitDefinition> traits, string moduleName)
        {
            var values = traits.ToList();
            ValidateUniqueIds(values.Select(x => x.Id), "trait");
            var sb = new StringBuilder().Append("module ").Append(ValidateScriptToken(moduleName, "module name")).AppendLine().AppendLine("{");
            foreach (var item in values)
            {
                ValidateScriptToken(item.Id, "trait ID");
                sb.Append("    character_trait_definition ").AppendLine(item.Id).AppendLine("    {");
                AppendScriptProperty(sb, "IsProfessionTrait", LuaBool(item.IsProfessionTrait));
                AppendScriptProperty(sb, "DisabledInMultiplayer", LuaBool(item.RemoveInMP));
                AppendScriptProperty(sb, "CharacterTrait", item.Id);
                AppendScriptProperty(sb, "Cost", item.Cost.ToString(CultureInfo.InvariantCulture));
                AppendScriptProperty(sb, "UIName", item.TranslationKey);
                AppendScriptProperty(sb, "UIDescription", item.DescriptionKey);
                AppendScriptList(sb, "Recipes", item.FreeRecipes);
                AppendScriptBoosts(sb, item.XpBoosts);
                foreach (var property in item.ExtraProperties)
                    AppendScriptProperty(sb, property.Key, property.Value);
                sb.AppendLine("    }");
            }
            return sb.AppendLine("}").ToString();
        }

        public static List<LocalizationEntry> ParseLocalization(string text, bool build42)
        {
            if (string.IsNullOrWhiteSpace(text))
                return new();
            if (build42)
            {
                using var document = JsonDocument.Parse(text, new JsonDocumentOptions { AllowTrailingCommas = true, CommentHandling = JsonCommentHandling.Skip });
                if (document.RootElement.ValueKind != JsonValueKind.Object)
                    throw new FormatException("A Build 42 localization file must contain a JSON object.");
                return document.RootElement.EnumerateObject()
                    .Select(x => new LocalizationEntry { Key = x.Name, Value = x.Value.ValueKind == JsonValueKind.String ? x.Value.GetString() ?? "" : x.Value.ToString() })
                    .ToList();
            }

            var body = Regex.Match(text, @"\{(?<body>.*)\}", RegexOptions.Singleline).Groups["body"].Value;
            return Regex.Matches(body, "(?m)^[ \\t]*(?<key>[A-Za-z0-9_.-]+)[ \\t]*=[ \\t]*(?<quote>['\\\"])(?<value>.*?)\\k<quote>[ \\t]*,?[ \\t]*\\r?$")
                .Cast<Match>()
                .Select(x => new LocalizationEntry { Key = x.Groups["key"].Value, Value = UnescapeLua(x.Groups["value"].Value) })
                .ToList();
        }

        public static string BuildLocalization(IEnumerable<LocalizationEntry> entries, bool build42, string category)
        {
            var values = entries.ToList();
            var duplicate = values.GroupBy(x => x.Key.Trim(), StringComparer.Ordinal).FirstOrDefault(x => string.IsNullOrWhiteSpace(x.Key) || x.Count() > 1);
            if (duplicate != null)
                throw new InvalidOperationException(string.IsNullOrWhiteSpace(duplicate.Key) ? "Localization keys cannot be empty." : $"Localization key '{duplicate.Key}' is duplicated.");
            if (build42)
            {
                var ordered = values.ToDictionary(x => x.Key.Trim(), x => x.Value, StringComparer.Ordinal);
                return JsonSerializer.Serialize(ordered, new JsonSerializerOptions { WriteIndented = true }) + Environment.NewLine;
            }

            var sb = new StringBuilder().Append(category).Append("_EN = {").AppendLine();
            foreach (var entry in values)
                sb.Append("    ").Append(entry.Key.Trim()).Append(" = ").Append(Quote(entry.Value)).AppendLine(",");
            return sb.AppendLine("}").ToString();
        }

        public static List<SandboxOptionDefinition> ParseSandboxOptions(string text)
        {
            var result = new List<SandboxOptionDefinition>();
            var matches = Regex.Matches(text, @"\boption\s+(?<id>[A-Za-z_][A-Za-z0-9_.]*)\s*(?:=\s*)?\{", RegexOptions.IgnoreCase);
            foreach (Match match in matches)
            {
                var open = text.IndexOf('{', match.Index + match.Length - 1);
                var close = FindClosingBrace(text, open);
                if (open < 0 || close < 0)
                    continue;
                var option = new SandboxOptionDefinition { Id = match.Groups["id"].Value };
                foreach (var rawProperty in SplitArguments(text[(open + 1)..close]))
                {
                    var property = Regex.Match(rawProperty, @"^\s*(?<key>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?<value>.*?)\s*$", RegexOptions.Singleline);
                    if (property.Success)
                        SetSandboxProperty(option, property.Groups["key"].Value, property.Groups["value"].Value.Trim());
                }
                result.Add(option);
            }
            return result;
        }

        public static string BuildSandboxOptions(IEnumerable<SandboxOptionDefinition> options)
        {
            var values = options.ToList();
            var duplicate = values.GroupBy(x => x.Id.Trim(), StringComparer.OrdinalIgnoreCase).FirstOrDefault(x => string.IsNullOrWhiteSpace(x.Key) || x.Count() > 1);
            if (duplicate != null)
                throw new InvalidOperationException(string.IsNullOrWhiteSpace(duplicate.Key) ? "Sandbox option IDs cannot be empty." : $"Sandbox option '{duplicate.Key}' is duplicated.");
            var sb = new StringBuilder().AppendLine("VERSION = 1,").AppendLine();
            foreach (var item in values)
            {
                if (!Regex.IsMatch(item.Id, @"^[A-Za-z_][A-Za-z0-9_.]*$"))
                    throw new InvalidOperationException($"'{item.Id}' is not a valid sandbox option ID.");
                if (string.IsNullOrWhiteSpace(item.Type))
                    throw new InvalidOperationException($"Sandbox option '{item.Id}' needs a type.");
                sb.Append("option ").Append(item.Id.Trim()).AppendLine(" {");
                AppendSandboxProperty(sb, "type", item.Type);
                AppendSandboxProperty(sb, "default", item.Default);
                AppendSandboxProperty(sb, "min", item.Min);
                AppendSandboxProperty(sb, "max", item.Max);
                AppendSandboxProperty(sb, "step", item.Step);
                AppendSandboxProperty(sb, "numValues", item.NumValues);
                AppendSandboxProperty(sb, "page", item.Page);
                AppendSandboxProperty(sb, "translation", item.Translation);
                AppendSandboxProperty(sb, "tooltip", item.Tooltip);
                AppendSandboxProperty(sb, "valueTranslation", item.ValueTranslation);
                foreach (var extra in item.ExtraProperties.OrderBy(x => x.Key, StringComparer.OrdinalIgnoreCase))
                    AppendSandboxProperty(sb, extra.Key, extra.Value);
                sb.AppendLine("}").AppendLine();
            }
            return sb.ToString();
        }

        public static string GetLocalizationPath(ModTarget target, string language, string category)
        {
            language = ValidateSegment(language, "language").ToUpperInvariant();
            category = ValidateSegment(category, "category");
            var extension = target.Build >= 42 ? ".json" : ".txt";
            return Path.Combine(target.Path, "media", "lua", "shared", "Translate", language, category + extension);
        }

        public static void SaveWithBackup(string path, string content)
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path) ?? throw new InvalidOperationException("The file has no parent folder."));
            if (File.Exists(path))
                File.Copy(path, path + ".pztools.bak", true);
            File.WriteAllText(path, content, new UTF8Encoding(false));
        }

        private static StringBuilder NewLuaBuilder(string function) => new StringBuilder()
            .AppendLine(GeneratedHeader).AppendLine()
            .Append("local function ").Append(function).AppendLine("()");

        private static string FinishLuaBuilder(StringBuilder sb, string function) => sb.AppendLine("end").AppendLine()
            .Append("Events.OnGameBoot.Add(").Append(function).AppendLine(")").ToString();

        private static void AddBoosts(ICollection<PerkBoostDefinition> boosts, string text, string variable)
        {
            foreach (Match boost in Regex.Matches(text, $@"\b{Regex.Escape(variable)}\s*:\s*addXPBoost\s*\(\s*Perks\.(?<perk>[A-Za-z_][A-Za-z0-9_]*)\s*,\s*(?<level>-?\d+)\s*\)", RegexOptions.Singleline))
                if (!IsLineCommented(text, boost.Index))
                    boosts.Add(new PerkBoostDefinition { Perk = boost.Groups["perk"].Value, Level = ParseInt(boost.Groups["level"].Value) });
        }

        private static IEnumerable<(string Id, string Body)> FindScriptDefinitions(string text, string keyword)
        {
            foreach (Match match in Regex.Matches(text, $@"\b{Regex.Escape(keyword)}\s+(?<id>[^\s{{]+)\s*\{{", RegexOptions.IgnoreCase))
            {
                if (IsLineCommented(text, match.Index))
                    continue;
                var open = text.IndexOf('{', match.Index + match.Length - 1);
                var close = FindClosingBrace(text, open);
                if (open >= 0 && close > open)
                    yield return (match.Groups["id"].Value.Trim(), text[(open + 1)..close]);
            }
        }

        private static Dictionary<string, string> ParseScriptProperties(string body)
        {
            var properties = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (Match match in Regex.Matches(body, @"(?m)^\s*(?<key>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?<value>.*?)\s*,?\s*$"))
                properties[match.Groups["key"].Value] = match.Groups["value"].Value.Trim().TrimEnd(',').TrimEnd();
            return properties;
        }

        private static string ScriptProperty(IReadOnlyDictionary<string, string> properties, string key)
            => properties.TryGetValue(key, out var value) ? value : "";

        private static void AddScriptList(ICollection<string> target, IReadOnlyDictionary<string, string> properties, params string[] keys)
        {
            var value = keys.Select(key => ScriptProperty(properties, key)).FirstOrDefault(x => !string.IsNullOrWhiteSpace(x));
            if (string.IsNullOrWhiteSpace(value))
                return;
            foreach (var item in value.Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
                target.Add(item);
        }

        private static void AddScriptBoosts(ICollection<PerkBoostDefinition> target, IReadOnlyDictionary<string, string> properties)
        {
            foreach (var item in ScriptProperty(properties, "XPBoosts").Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
            {
                var parts = item.Split('=', 2, StringSplitOptions.TrimEntries);
                if (parts.Length == 2 && int.TryParse(parts[1], NumberStyles.Integer, CultureInfo.InvariantCulture, out var level))
                    target.Add(new PerkBoostDefinition { Perk = parts[0], Level = level });
            }
        }

        private static void CopyExtraProperties(IDictionary<string, string> target, IReadOnlyDictionary<string, string> source, params string[] known)
        {
            var knownSet = known.ToHashSet(StringComparer.OrdinalIgnoreCase);
            foreach (var property in source.Where(x => !knownSet.Contains(x.Key)))
                target[property.Key] = property.Value;
        }

        private static void AppendScriptProperty(StringBuilder sb, string key, string? value)
        {
            if (!string.IsNullOrWhiteSpace(value))
                sb.Append("        ").Append(key).Append(" = ").Append(value.Trim()).AppendLine(",");
        }

        private static void AppendScriptList(StringBuilder sb, string key, IEnumerable<string> values)
        {
            var value = string.Join(';', values.Where(x => !string.IsNullOrWhiteSpace(x)).Select(x => x.Trim()));
            AppendScriptProperty(sb, key, value);
        }

        private static void AppendScriptBoosts(StringBuilder sb, IEnumerable<PerkBoostDefinition> boosts)
            => AppendScriptProperty(sb, "XPBoosts", string.Join(';', boosts.Select(x => $"{ValidatePerk(x.Perk)}={x.Level.ToString(CultureInfo.InvariantCulture)}")));

        private static IEnumerable<(int Start, string Arguments)> FindCalls(string text, string name)
        {
            var offset = 0;
            while ((offset = text.IndexOf(name, offset, StringComparison.Ordinal)) >= 0)
            {
                if (IsLineCommented(text, offset))
                {
                    offset += name.Length;
                    continue;
                }
                var open = text.IndexOf('(', offset + name.Length);
                if (open < 0)
                    yield break;
                var close = FindClosingParenthesis(text, open);
                if (close < 0)
                    yield break;
                yield return (offset, text[(open + 1)..close]);
                offset = close + 1;
            }
        }

        private static int FindClosingParenthesis(string text, int open)
        {
            var depth = 0;
            char quote = '\0';
            var escaped = false;
            for (var i = open; i < text.Length; i++)
            {
                var c = text[i];
                if (quote != '\0')
                {
                    if (escaped)
                        escaped = false;
                    else if (c == '\\')
                        escaped = true;
                    else if (c == quote)
                        quote = '\0';
                    continue;
                }
                if (c is '\'' or '\"')
                {
                    quote = c;
                    continue;
                }
                if (c == '(')
                    depth++;
                else if (c == ')' && --depth == 0)
                    return i;
            }
            return -1;
        }

        private static int FindClosingBrace(string text, int open)
        {
            if (open < 0)
                return -1;
            var depth = 0;
            for (var i = open; i < text.Length; i++)
            {
                if (text[i] == '{')
                    depth++;
                else if (text[i] == '}' && --depth == 0)
                    return i;
            }
            return -1;
        }

        private static void SetSandboxProperty(SandboxOptionDefinition item, string key, string value)
        {
            switch (key.ToLowerInvariant())
            {
                case "type":
                    item.Type = value;
                    break;
                case "default":
                    item.Default = value;
                    break;
                case "min":
                    item.Min = value;
                    break;
                case "max":
                    item.Max = value;
                    break;
                case "step":
                    item.Step = value;
                    break;
                case "numvalues":
                    item.NumValues = value;
                    break;
                case "page":
                    item.Page = value;
                    break;
                case "translation":
                    item.Translation = value;
                    break;
                case "tooltip":
                    item.Tooltip = value;
                    break;
                case "valuetranslation":
                    item.ValueTranslation = value;
                    break;
                default:
                    item.ExtraProperties[key] = value;
                    break;
            }
        }

        private static void AppendSandboxProperty(StringBuilder sb, string key, string? value)
        {
            if (!string.IsNullOrWhiteSpace(value))
                sb.Append("    ").Append(key).Append(" = ").Append(value.Trim()).AppendLine(",");
        }

        private static void AddRecipes(ICollection<string> recipes, string text, string variable)
        {
            foreach (Match recipe in Regex.Matches(text, $"\\b{Regex.Escape(variable)}\\s*:\\s*getFreeRecipes\\s*\\(\\s*\\)\\s*:\\s*add\\s*\\(\\s*(['\\\"])(?<value>.*?)\\1\\s*\\)", RegexOptions.Singleline))
                if (!IsLineCommented(text, recipe.Index))
                    recipes.Add(recipe.Groups["value"].Value);
        }

        private static bool IsLineCommented(string text, int index)
        {
            var lineStart = text.LastIndexOf('\n', Math.Max(0, index - 1)) + 1;
            var comment = text.IndexOf("--", lineStart, StringComparison.Ordinal);
            return comment >= lineStart && comment < index;
        }

        private static List<string> SplitArguments(string args)
        {
            var result = new List<string>();
            var start = 0;
            var depth = 0;
            char quote = '\0';
            var escaped = false;
            for (var i = 0; i < args.Length; i++)
            {
                var c = args[i];
                if (quote != '\0')
                {
                    if (escaped)
                        escaped = false;
                    else if (c == '\\')
                        escaped = true;
                    else if (c == quote)
                        quote = '\0';
                    continue;
                }
                if (c is '\'' or '\"')
                    quote = c;
                else if (c == '(')
                    depth++;
                else if (c == ')')
                    depth--;
                else if (c == ',' && depth == 0)
                {
                    result.Add(args[start..i].Trim());
                    start = i + 1;
                }
            }
            result.Add(args[start..].Trim());
            return result;
        }

        private static string? FindAssignedVariable(string text, int callStart)
        {
            var lineStart = text.LastIndexOf('\n', Math.Max(0, callStart - 1)) + 1;
            var prefix = text[lineStart..callStart];
            var match = Regex.Match(prefix, @"(?:local\s+)?(?<name>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*$");
            return match.Success ? match.Groups["name"].Value : null;
        }

        private static string GetTextKey(string expression)
        {
            var match = Regex.Match(expression, "getText\\s*\\(\\s*(['\\\"])(?<value>.*?)\\1\\s*\\)", RegexOptions.Singleline);
            return match.Success ? match.Groups["value"].Value : LuaString(expression);
        }

        private static string LuaString(string value)
        {
            value = value.Trim();
            return value.Length >= 2 && (value[0] is '\'' or '\"') && value[^1] == value[0] ? UnescapeLua(value[1..^1]) : value;
        }

        private static string UnescapeLua(string value) => value.Replace("\\\"", "\"").Replace("\\'", "'").Replace("\\n", "\n").Replace("\\\\", "\\");
        private static int ParseInt(string value) => int.TryParse(value.Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var parsed) ? parsed : 0;
        private static bool ParseBool(string value) => value.Trim().Equals("true", StringComparison.OrdinalIgnoreCase);
        private static string LuaBool(bool value) => value ? "true" : "false";
        private static string Quote(string value) => $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "").Replace("\n", "\\n")}\"";
        private static string SafeId(ModProject project) => string.IsNullOrWhiteSpace(project.ModInfo.Id) ? Regex.Replace(project.Name, "[^A-Za-z0-9_]", "") : Regex.Replace(project.ModInfo.Id, "[^A-Za-z0-9_]", "");
        private static void ValidateId(string value, string kind)
        {
            if (string.IsNullOrWhiteSpace(value))
                throw new InvalidOperationException($"Every {kind} needs an ID.");
        }
        private static void ValidateUniqueIds(IEnumerable<string> ids, string kind)
        {
            var duplicate = ids.GroupBy(x => x?.Trim() ?? "", StringComparer.OrdinalIgnoreCase).FirstOrDefault(x => x.Count() > 1);
            if (duplicate != null)
                throw new InvalidOperationException($"The {kind} ID '{duplicate.Key}' is duplicated.");
        }
        private static string ValidatePerk(string value) => Regex.IsMatch(value ?? "", @"^[A-Za-z_][A-Za-z0-9_]*$") ? value! : throw new InvalidOperationException($"'{value}' is not a valid perk name.");
        private static string ValidateScriptToken(string value, string label) => Regex.IsMatch(value ?? "", @"^[A-Za-z_][A-Za-z0-9_.:-]*$") ? value! : throw new InvalidOperationException($"'{value}' is not a valid {label}.");
        private static string ValidateSegment(string value, string label) => Regex.IsMatch(value ?? "", @"^[A-Za-z0-9_-]+$") ? value! : throw new InvalidOperationException($"The {label} may only contain letters, numbers, underscores, and hyphens.");
    }
}
